#!/bin/bash

hugo
git add --all
git status

echo "Publish above changes? [y/n]"
read continue

if [ "$continue" != "y" ]; then
	exit 1
fi

echo "Enter git commit message:"
read message

git commit -m "$message"
git push origin master

echo "Published!"

